<?php
$courses= array(
    GEN101 => "Use of English"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
    TLE101 => "INTRODUCTIO TO TELECOMS ENGINEERING"
);

?>